### PR TITLE
Added a trailing slash to the expected location header.

### PR DESCRIPTION
**Pull request by RutgerUijtendaal**
This fixes an issue where even though credentials were correct the "Invalid credentials" error was thrown.

### CODE REVIEW

**Comment by primarilysnark** [comment]
First, apologies on not responding six days ago. It's been a while since I worked on this project and didn't expect anyone else to find it. I'm kind of amazed that you did.

Second, I'd prefer a stronger system for verifying the URL than a flaky string comparison. What about pulling in `url-parse` and using it to create a validated format for the location URL?

**Review by primarilysnark — CHANGES_REQUESTED** [review]
First, apologies on not responding six days ago. It's been a while since I worked on this project and didn't expect anyone else to find it. I'm kind of amazed that you did.

Second, I'd prefer a stronger system for verifying the URL than a flaky string comparison. What about pulling in `url-parse` and using it to create a validated format for the location URL?

**Comment by RutgerUijtendaal** [comment]
No problem, thought I'd check up on the PR. I stumbled upon this and after a small change it came in very useful for testing on the Roll20 environment. 

Building a URL from the string would indeed be a more robust option. If I find the time I'll look into it.

**Comment by primarilysnark** [comment]
If you don't have time to look at it, I can create and publish a fix. Thanks for bringing it to my attention either way!

**Pull request closed without merging**
